### ISSUE TITLE
Problema con el CSS

### ISSUE THREAD

**Issue by ellewen** [notepad0n11n3/hyperblog#2]
## En que puedo ayudarte.

El repositorio ha dejado de funcionar? [ ]
No encuentras algun archivo del codigo [ ]
otro [ X]

Especifica: 
No encuentro los archivos css deltro del codigo

**Comment by notepad0n11n3** [comment]
re lolo... buscar en el repositorio, todos los archivos se encuentran ah[i. XD

**Comment by notepad0n11n3** [comment]
BYE

**Comment by ellewen** [comment]
:u
